<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Str;

class Product extends Model
{
    use SoftDeletes;

    protected $fillable = [
        'code', 'name', 'currency', 'price', 'merchant_id', 'description', 'deleted_at', 'created_at', 'updated_at'
    ];

    public function merchant(): BelongsTo
    {
        return $this->belongsTo(User::class, 'merchant_id', 'id');
    }

    protected static function booted()
    {
        parent::booted(); // TODO: Change the autogenerated stub

        static::created(function ($model) {
            $model->code = self::generateProductCode($model);
            $model->save();
        });
    }

    protected static function generateProductCode($model): string
    {
        $part2 = Str::substr(time(), -4);
        return 'item' . str_pad($model->id . $part2, 5, 'x41', STR_PAD_LEFT);
    }
}
