<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Str;

class Purchase extends Model
{
    use SoftDeletes;

    protected $fillable = [
        'merchant_id', 'id', 'code', 'payment_reference', 'status', 'currency', 'totalamount', 'merchant_commission',
        'created_at', 'updated_at'
    ];

    public function merchant(): BelongsTo
    {
        return $this->belongsTo(User::class, 'merchant_id', 'id');
    }

    protected static function booted()
    {
        parent::booted(); // TODO: Change the autogenerated stub

        static::created(function ($model) {
            $model->code = self::generatePurchaseCode($model);
            $model->save();
        });
    }

    protected static function generatePurchaseCode($model): string
    {
        $part2 = Str::substr(time(), -4);
        return 'purchase' . str_pad($model->id . $part2, 5, 'x91', STR_PAD_LEFT);
    }


}
